[package]
name = "DynaRust"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
tokio = "1.44.2"
chrono = "0.4.40"
reqwest = { version = "0.12.15", features = ["json"] }
futures-util = "0.3.31"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }

